### ISSUE TITLE
Confused about gene weights and gene selection.

### ISSUE THREAD

**Issue by JHovelly** [cliffren/PENCIL#4]
Hi cliffren,

Thanks for your great algorithm! It really helps our research.
I'm confused about how to select genes according to gene weights. In the paper I learned, you selected genes with _w ≠ 0._. But in my data, all genes have _w ≠ 0._, though most of them are so small, like 5.765585e-06. So I guess there is a threhold or I made a mistake and got wrong gene weights?

It would be appreciated if you could help me.
plus : I got gene weights  through _gene_weights = model.gene_weights(plot=True)_

Best,
JHovelly

**Comment by cliffren** [comment]
Hi JHovelly, 

I apologize for my late response，the lost email kept me from noticing your question. First of all, thanks for using our algorithm. 

In our algorithm, gene selection relies on L1 sparse regularization, which means that only a small number of representative genes will be selected. In your dataset, all genes have a weight of 0. It is possible that the default regularization weights are too large for your dataset, try reducing them to **_1e-4, 1e-5..._** , until a small number of representative genes are indeed selected.

After that, all differential genes of correlation can be found by re-comparing the expression of the un-rejected cells according to the predicted groups (e.g. using the _**Findmarkers**_ function in _seurat_).

Hope these can  help you. If there are still problems, please feel free to give feedback.

Best, 
Tao Ren
